#!/bin/bash -e

echo "Accessing a running or recent build's steps: http://concourse.ci/fly-intercept.html"

USAGE="Usage: bin/hijack <target_name> <pipeline_name> <job_name> <build>"

if [[ $# < 4 ]]; then
  echo "Illegal number of parameters"
  echo $USAGE
  exit
fi

fly -t $1 intercept -j $2/$3 -b $4

#fly -t home intercept -j pcf-installer/lab-ops-manager -b 7 -s deploy-ops-manager
#fly -t home intercept --check pcf-installer/pcf-installer-spike
#fly -t home intercept -j pcf-installer/lab-elastic-runtime -b 6
