#!/bin/bash -e

echo 'Unpause pipeline on a particular target'

USAGE="Usage: bin/unpause-pipeline target_name pipeline_name"

if [[ $# -ne 2 ]]; then
  echo "Illegal number of parameters"
  echo $USAGE
  exit
fi

fly -t $1 unpause-pipeline --pipeline $2
